name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Testing pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    env:
      USE_LOCAL_DEFAULT: TRUE
      LOCALTERRA_PATH: ./LocalTerra
      SCRIPTS_PATH: ../scripts
      ARTIFACTS_PATH: ../artifacts
    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Cancelling previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checking out repository
      uses: actions/checkout@v3

    - run: $GITHUB_WORKSPACE/scripts/build_release.sh

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: tests/package-lock.json

    - run: npm ci

    - name: Linting tests...
      run: npm run lint

    - name: Cloning LocalTerra...
      run: |
        git clone --depth 1 https://github.com/terra-money/LocalTerra.git
        sed -E -i '/timeout_(propose|prevote|precommit|commit)/s/[0-9]+m?s/200ms/' LocalTerra/config/config.toml

    - name: Running integration tests
      run: npm test
