name: Contracts formatting checks and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
